on: [push, pull_request, workflow_dispatch]

name: Safe Hash

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:

      - name: Install Rust Nightly (2025-01-01)
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2025-01-01
          override: true

      - name: Checkout Sources
        uses: actions/checkout@v4

      - name: Restore Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Run tests
        run: |
          cargo build
          cargo test -- --nocapture

  decline-openssl-dependencies:
    name: Decline openssl
    runs-on: ubuntu-latest
    steps:

      - name: Install Rust Nightly (2025-01-01)
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2025-01-01
          override: true

      - name: Checkout Sources
        uses: actions/checkout@v4

      - name: Restore Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Run tests
        run: |
          ! cargo tree -i openssl --target all
